# MC Rebedrock options
game.version=ReBedrock beta2
window.width=960
window.height=720
window.maximized=false
gui.scale=0
render.distance=4
render.fpsLimit=120
render.anisotropy=8
render.antiAliasing=true
render.viewBobbing=true
audio.masterVolume=0.8
lighting.dynamic=false
lighting.smooth=true
text.language=en_us
text.forceUnicodeFont=false
