// The build-time baking step for D-1.
//
// Reads a directory of datapack JSON files (the demo dataset) through the very
// same codec the runtime overlay path uses, then emits a constexpr C++ table so
// the built-in floor lands in `.rodata` and startup parses nothing. This is the
// "internal content baked at build time" half of the two-layer design: the
// generator runs offline (it is a manual tool, built only under
// -DMC_REBEDROCK_BUILD_TOOLS=ON), its committed output is what ordinary builds
// compile, and re-running it is how the floor is regenerated from source JSON —
// the same workflow BlockTags' hand-transcribed constexpr defaults follow, but
// mechanised and codec-checked so the baked table cannot drift from the JSON.
//
// Usage: bake_demo_data <source-dir> [output.inc]
//   source-dir  directory of *.json records; the file stem becomes the id path
//   output.inc  file to write (stdout if omitted)

#include "core/Json.hpp"
#include "data/Codec.hpp"
#include "data/DemoData.hpp"

#include <algorithm>
#include <array>
#include <cstdio>
#include <exception>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace {

using mc::data::demo::DemoRecord;

struct BakedEntry {
    std::string name; // minecraft:<stem>
    DemoRecord record;
};

// Escapes a string so it is a valid C++ string literal body.
std::string cppString(std::string_view text) {
    std::string out = "\"";
    for (const char c : text) {
        switch (c) {
            case '"': out += "\\\""; break;
            case '\\': out += "\\\\"; break;
            case '\n': out += "\\n"; break;
            case '\r': out += "\\r"; break;
            case '\t': out += "\\t"; break;
            default: out.push_back(c);
        }
    }
    out.push_back('"');
    return out;
}

// Round-trip-exact double literal.
std::string cppDouble(double value) {
    std::array<char, 32> buffer{};
    std::snprintf(buffer.data(), buffer.size(), "%.17g", value);
    return std::string{buffer.data()};
}

std::string readFile(const std::filesystem::path& path) {
    std::ifstream input{path, std::ios::binary};
    std::ostringstream contents;
    contents << input.rdbuf();
    return contents.str();
}

} // namespace

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: %s <source-dir> [output.inc]\n", argv[0]);
        return 2;
    }
    const std::filesystem::path sourceDir{argv[1]};

    // Sort by filename so the generated ids are assigned deterministically,
    // regardless of directory iteration order.
    std::vector<std::filesystem::path> files;
    for (const auto& entry : std::filesystem::directory_iterator{sourceDir}) {
        if (entry.is_regular_file() && entry.path().extension() == ".json") {
            files.push_back(entry.path());
        }
    }
    std::sort(files.begin(), files.end());

    std::vector<BakedEntry> baked;
    for (const auto& file : files) {
        const std::string text = readFile(file);
        mc::core::Json root;
        try {
            root = mc::core::Json::parse(text);
        } catch (const std::exception& error) {
            std::fprintf(stderr, "bake: %s: %s\n", file.string().c_str(), error.what());
            return 1;
        }
        DemoRecord record;
        if (!mc::data::Codec<DemoRecord>::read(root, record)) {
            std::fprintf(stderr, "bake: %s: does not match the DemoRecord codec\n",
                         file.string().c_str());
            return 1;
        }
        baked.push_back(BakedEntry{"minecraft:" + file.stem().string(), std::move(record)});
    }

    std::string out;
    out += "// GENERATED by tools/bake/bake_demo_data.cpp — do not edit by hand.\n";
    out += "// Regenerate: mc_rebedrock_bake_demo_data <source-dir> <this-file>\n";
    out += "// This is D-1's baked floor: a constexpr table in .rodata, zero startup parse.\n";
    out += "#pragma once\n\n";
    out += "namespace mc::data::demo {\n\n";

    // Emit a named steps array per record with a non-empty list; an empty list
    // becomes an empty span literal `{}` so no zero-length C array is generated.
    for (std::size_t index = 0; index < baked.size(); ++index) {
        const auto& steps = baked[index].record.steps;
        if (steps.empty()) {
            continue;
        }
        out += "inline constexpr std::int32_t kDemoSteps_" + std::to_string(index) + "[] = {";
        for (std::size_t step = 0; step < steps.size(); ++step) {
            if (step != 0U) out += ", ";
            out += std::to_string(steps[step]);
        }
        out += "};\n";
    }
    out += "\ninline constexpr BakedDemoRecord kDemoBakedTable[] = {\n";
    for (std::size_t index = 0; index < baked.size(); ++index) {
        const auto& record = baked[index].record;
        out += "    {";
        out += cppString(baked[index].name) + ", ";
        out += std::to_string(record.weight) + ", ";
        out += cppString(record.label) + ", ";
        out += record.steps.empty() ? std::string{"{}"}
                                    : ("kDemoSteps_" + std::to_string(index));
        out += ", ";
        out += record.enabled ? "true" : "false";
        out += ", ";
        out += record.scale.has_value() ? "true" : "false";
        out += ", ";
        out += cppDouble(record.scale.value_or(0.0));
        out += "},\n";
    }
    out += "};\n\n";
    out += "} // namespace mc::data::demo\n";

    if (argc >= 3) {
        std::ofstream output{argv[2], std::ios::binary};
        output << out;
        if (!output) {
            std::fprintf(stderr, "bake: cannot write %s\n", argv[2]);
            return 1;
        }
    } else {
        std::fputs(out.c_str(), stdout);
    }
    return 0;
}
